-- Carga masiva SDT DROPS (mayo 2026)
-- Productos con: nombre, descripcion, categoria, precio base, precios por tramo, imagen (vacia), colores (vacio)

alter table public.products add column if not exists description text;
alter table public.products add column if not exists tier_prices jsonb;
alter table public.products add column if not exists colors jsonb;

with data as (
  select jsonb_build_array(
    jsonb_build_object('id','cam-1','name','Remeras De Argentina Suplente Tailandesa G5','cat','Camisetas','description','Lista mayorista Santi Villalba','price',29000,'stock',50,'img','','tier_prices',jsonb_build_array(jsonb_build_object('minQty',10,'maxQty',29,'unitPrice',29000),jsonb_build_object('minQty',30,'maxQty',49,'unitPrice',26700),jsonb_build_object('minQty',50,'maxQty',99,'unitPrice',24800),jsonb_build_object('minQty',100,'unitPrice',20000))),
    jsonb_build_object('id','cam-2','name','Camiseta Calidad Jugador G5 Tailandesa','cat','Camisetas','description','Lista mayorista Santi Villalba','price',29000,'stock',50,'img','','tier_prices',jsonb_build_array(jsonb_build_object('minQty',10,'maxQty',19,'unitPrice',29000),jsonb_build_object('minQty',20,'maxQty',49,'unitPrice',26500),jsonb_build_object('minQty',50,'maxQty',99,'unitPrice',24900),jsonb_build_object('minQty',100,'unitPrice',20000))),

    jsonb_build_object('id','st-1','name','Set Hoppies 3 en 1 + Stickers','cat','Stanley','description','2000 ml, 900 ml, 300 ml','price',11400,'stock',50,'img','','tier_prices',jsonb_build_array(jsonb_build_object('minQty',10,'maxQty',24,'unitPrice',11400),jsonb_build_object('minQty',25,'maxQty',47,'unitPrice',10200),jsonb_build_object('minQty',48,'unitPrice',8990))),
    jsonb_build_object('id','st-2','name','Vaso Cafetero 500ml con sensor de temperatura','cat','Stanley','description','Linea Stanley','price',13400,'stock',50,'img','','tier_prices',jsonb_build_array(jsonb_build_object('minQty',5,'maxQty',9,'unitPrice',13400),jsonb_build_object('minQty',10,'maxQty',19,'unitPrice',12550),jsonb_build_object('minQty',20,'maxQty',29,'unitPrice',11890),jsonb_build_object('minQty',30,'maxQty',39,'unitPrice',11150),jsonb_build_object('minQty',40,'maxQty',49,'unitPrice',9820),jsonb_build_object('minQty',50,'unitPrice',9100))),
    jsonb_build_object('id','st-3','name','Botella con pico 350ml','cat','Stanley','description','Linea Stanley','price',11000,'stock',50,'img','','tier_prices',jsonb_build_array(jsonb_build_object('minQty',5,'maxQty',9,'unitPrice',11000),jsonb_build_object('minQty',10,'maxQty',19,'unitPrice',10620),jsonb_build_object('minQty',20,'maxQty',29,'unitPrice',9950),jsonb_build_object('minQty',30,'maxQty',39,'unitPrice',9400),jsonb_build_object('minQty',40,'maxQty',49,'unitPrice',8600),jsonb_build_object('minQty',50,'unitPrice',7900))),
    jsonb_build_object('id','st-4','name','Botella con pico 500ml','cat','Stanley','description','Linea Stanley','price',11400,'stock',50,'img','','tier_prices',jsonb_build_array(jsonb_build_object('minQty',5,'maxQty',9,'unitPrice',11400),jsonb_build_object('minQty',10,'maxQty',19,'unitPrice',10750),jsonb_build_object('minQty',20,'maxQty',29,'unitPrice',9990),jsonb_build_object('minQty',30,'maxQty',39,'unitPrice',9450),jsonb_build_object('minQty',40,'maxQty',49,'unitPrice',8690),jsonb_build_object('minQty',50,'unitPrice',7950))),
    jsonb_build_object('id','st-5','name','Botella con pico 750ml','cat','Stanley','description','Linea Stanley','price',11000,'stock',50,'img','','tier_prices',jsonb_build_array(jsonb_build_object('minQty',5,'maxQty',9,'unitPrice',11000),jsonb_build_object('minQty',10,'maxQty',19,'unitPrice',10620),jsonb_build_object('minQty',20,'maxQty',29,'unitPrice',9950),jsonb_build_object('minQty',30,'maxQty',39,'unitPrice',9400),jsonb_build_object('minQty',40,'maxQty',49,'unitPrice',8600),jsonb_build_object('minQty',50,'unitPrice',7900))),
    jsonb_build_object('id','st-6','name','Botella con filtro 800ml','cat','Stanley','description','Linea Stanley','price',13400,'stock',50,'img','','tier_prices',jsonb_build_array(jsonb_build_object('minQty',5,'maxQty',9,'unitPrice',13400),jsonb_build_object('minQty',10,'maxQty',24,'unitPrice',12500),jsonb_build_object('minQty',25,'maxQty',49,'unitPrice',10600),jsonb_build_object('minQty',50,'unitPrice',9400))),
    jsonb_build_object('id','st-7','name','Botella con pico 1000ml','cat','Stanley','description','Linea Stanley','price',15650,'stock',50,'img','','tier_prices',jsonb_build_array(jsonb_build_object('minQty',5,'maxQty',9,'unitPrice',15650),jsonb_build_object('minQty',10,'maxQty',19,'unitPrice',14090),jsonb_build_object('minQty',20,'maxQty',29,'unitPrice',12490),jsonb_build_object('minQty',30,'unitPrice',11190))),
    jsonb_build_object('id','st-8','name','Termo Stanley + Mate + Bombilla','cat','Stanley','description','Linea Stanley','price',24500,'stock',50,'img','','tier_prices',jsonb_build_array(jsonb_build_object('minQty',3,'maxQty',4,'unitPrice',24500),jsonb_build_object('minQty',5,'maxQty',9,'unitPrice',22300),jsonb_build_object('minQty',10,'maxQty',19,'unitPrice',19800),jsonb_build_object('minQty',20,'unitPrice',18400))),
    jsonb_build_object('id','st-9','name','Termo Stanley media manija 1L','cat','Stanley','description','Linea Stanley','price',14900,'stock',50,'img','','tier_prices',jsonb_build_array(jsonb_build_object('minQty',3,'maxQty',4,'unitPrice',14900),jsonb_build_object('minQty',5,'maxQty',9,'unitPrice',13200),jsonb_build_object('minQty',10,'maxQty',34,'unitPrice',11900),jsonb_build_object('minQty',35,'unitPrice',10400))),
    jsonb_build_object('id','st-10','name','Termo Stanley 1.2L System y Boca Ancha','cat','Stanley','description','Linea Stanley','price',20000,'stock',50,'img','','tier_prices',jsonb_build_array(jsonb_build_object('minQty',5,'maxQty',9,'unitPrice',20000),jsonb_build_object('minQty',10,'maxQty',19,'unitPrice',18900),jsonb_build_object('minQty',20,'unitPrice',16800))),
    jsonb_build_object('id','st-11','name','Vaso Quencher 1.2','cat','Stanley','description','Linea Stanley','price',15200,'stock',50,'img','','tier_prices',jsonb_build_array(jsonb_build_object('minQty',5,'maxQty',9,'unitPrice',15200),jsonb_build_object('minQty',10,'maxQty',19,'unitPrice',13400),jsonb_build_object('minQty',20,'maxQty',39,'unitPrice',11900),jsonb_build_object('minQty',40,'unitPrice',10400))),

    jsonb_build_object('id','may-17','name','Pava electrica','cat','Mayorista','description','Electrohogar','price',17000,'stock',50,'img','','tier_prices',jsonb_build_array(jsonb_build_object('minQty',5,'maxQty',9,'unitPrice',17000),jsonb_build_object('minQty',10,'maxQty',19,'unitPrice',15500),jsonb_build_object('minQty',20,'maxQty',31,'unitPrice',13500),jsonb_build_object('minQty',32,'unitPrice',11350))),
    jsonb_build_object('id','may-18','name','Set cocina 11 piezas','cat','Mayorista','description','Electrohogar','price',14500,'stock',50,'img','','tier_prices',jsonb_build_array(jsonb_build_object('minQty',5,'maxQty',9,'unitPrice',14500),jsonb_build_object('minQty',10,'maxQty',19,'unitPrice',13000),jsonb_build_object('minQty',20,'maxQty',49,'unitPrice',12000),jsonb_build_object('minQty',50,'maxQty',99,'unitPrice',10790),jsonb_build_object('minQty',100,'unitPrice',9490))),

    jsonb_build_object('id','may-1','name','AirPods Pro 2 con sello','cat','Mayorista','description','Audio y auriculares','price',18900,'stock',50,'img','','tier_prices',jsonb_build_array(jsonb_build_object('minQty',5,'maxQty',9,'unitPrice',18900),jsonb_build_object('minQty',10,'maxQty',19,'unitPrice',17900),jsonb_build_object('minQty',20,'maxQty',29,'unitPrice',17400),jsonb_build_object('minQty',30,'maxQty',39,'unitPrice',15900),jsonb_build_object('minQty',40,'maxQty',99,'unitPrice',15200),jsonb_build_object('minQty',100,'unitPrice',13800))),
    jsonb_build_object('id','may-2','name','AirPods Max','cat','Mayorista','description','Audio y auriculares','price',35000,'stock',50,'img','','tier_prices',jsonb_build_array(jsonb_build_object('minQty',1,'maxQty',2,'unitPrice',35000),jsonb_build_object('minQty',3,'maxQty',4,'unitPrice',29000),jsonb_build_object('minQty',5,'maxQty',9,'unitPrice',26000),jsonb_build_object('minQty',10,'maxQty',19,'unitPrice',24800),jsonb_build_object('minQty',20,'unitPrice',23000))),
    jsonb_build_object('id','may-3','name','Auriculares Xiaomi','cat','Mayorista','description','Audio y auriculares','price',10000,'stock',50,'img','','tier_prices',jsonb_build_array(jsonb_build_object('minQty',5,'maxQty',9,'unitPrice',10000),jsonb_build_object('minQty',10,'maxQty',19,'unitPrice',8800),jsonb_build_object('minQty',20,'maxQty',49,'unitPrice',7800),jsonb_build_object('minQty',50,'unitPrice',6750))),
    jsonb_build_object('id','may-4','name','JBL GO 4 / GO 4 RGB','cat','Mayorista','description','Audio y auriculares','price',17800,'stock',50,'img','','tier_prices',jsonb_build_array(jsonb_build_object('minQty',5,'maxQty',9,'unitPrice',17800),jsonb_build_object('minQty',10,'maxQty',19,'unitPrice',16150),jsonb_build_object('minQty',20,'maxQty',29,'unitPrice',15200),jsonb_build_object('minQty',30,'maxQty',49,'unitPrice',14200),jsonb_build_object('minQty',50,'maxQty',99,'unitPrice',13200),jsonb_build_object('minQty',100,'unitPrice',10400))),
    jsonb_build_object('id','may-5','name','JBL Flip 6','cat','Mayorista','description','Audio y auriculares','price',34000,'stock',50,'img','','tier_prices',jsonb_build_array(jsonb_build_object('minQty',3,'maxQty',4,'unitPrice',34000),jsonb_build_object('minQty',5,'maxQty',9,'unitPrice',32500),jsonb_build_object('minQty',10,'maxQty',19,'unitPrice',31400),jsonb_build_object('minQty',20,'maxQty',49,'unitPrice',29200),jsonb_build_object('minQty',50,'unitPrice',24100))),
    jsonb_build_object('id','may-6','name','JBL Flip 7','cat','Mayorista','description','Audio y auriculares','price',37000,'stock',50,'img','','tier_prices',jsonb_build_array(jsonb_build_object('minQty',3,'maxQty',4,'unitPrice',37000),jsonb_build_object('minQty',5,'maxQty',9,'unitPrice',33150),jsonb_build_object('minQty',10,'maxQty',19,'unitPrice',29250),jsonb_build_object('minQty',20,'unitPrice',27390))),

    jsonb_build_object('id','acc-1','name','Protectores de camara','cat','accesorios','description','Accesorios celular','price',3100,'stock',50,'img','','tier_prices',jsonb_build_array(jsonb_build_object('minQty',20,'maxQty',49,'unitPrice',3100),jsonb_build_object('minQty',50,'maxQty',99,'unitPrice',2700),jsonb_build_object('minQty',100,'unitPrice',2280))),
    jsonb_build_object('id','acc-2','name','Fundas silicone case / MagSafe','cat','accesorios','description','Accesorios celular','price',3300,'stock',50,'img','','tier_prices',jsonb_build_array(jsonb_build_object('minQty',20,'maxQty',29,'unitPrice',3300),jsonb_build_object('minQty',30,'maxQty',49,'unitPrice',2990),jsonb_build_object('minQty',50,'maxQty',99,'unitPrice',2700),jsonb_build_object('minQty',100,'maxQty',199,'unitPrice',2370),jsonb_build_object('minQty',200,'maxQty',499,'unitPrice',2050),jsonb_build_object('minQty',500,'unitPrice',1920))),
    jsonb_build_object('id','acc-3','name','Vidrios templados iPhone 11-17 Pro Max','cat','accesorios','description','Accesorios celular','price',1930,'stock',50,'img','','tier_prices',jsonb_build_array(jsonb_build_object('minQty',10,'maxQty',19,'unitPrice',1930),jsonb_build_object('minQty',20,'maxQty',29,'unitPrice',1770),jsonb_build_object('minQty',30,'maxQty',99,'unitPrice',1620),jsonb_build_object('minQty',100,'maxQty',199,'unitPrice',1380),jsonb_build_object('minQty',200,'maxQty',499,'unitPrice',1030),jsonb_build_object('minQty',500,'unitPrice',900))),
    jsonb_build_object('id','acc-4','name','Cargador MagSafe','cat','accesorios','description','Accesorios celular','price',13400,'stock',50,'img','','tier_prices',jsonb_build_array(jsonb_build_object('minQty',10,'maxQty',19,'unitPrice',13400),jsonb_build_object('minQty',20,'maxQty',29,'unitPrice',11900),jsonb_build_object('minQty',30,'maxQty',49,'unitPrice',10400),jsonb_build_object('minQty',50,'unitPrice',8900))),
    jsonb_build_object('id','acc-5','name','Combo cargador Apple','cat','accesorios','description','Accesorios celular','price',8150,'stock',50,'img','','tier_prices',jsonb_build_array(jsonb_build_object('minQty',10,'maxQty',19,'unitPrice',8150),jsonb_build_object('minQty',20,'maxQty',49,'unitPrice',7400),jsonb_build_object('minQty',50,'maxQty',99,'unitPrice',6390),jsonb_build_object('minQty',100,'maxQty',199,'unitPrice',5780),jsonb_build_object('minQty',200,'maxQty',299,'unitPrice',4800),jsonb_build_object('minQty',300,'maxQty',499,'unitPrice',4590),jsonb_build_object('minQty',500,'unitPrice',4450))),
    jsonb_build_object('id','acc-6','name','Battery Pack','cat','accesorios','description','Accesorios celular','price',15500,'stock',50,'img','','tier_prices',jsonb_build_array(jsonb_build_object('minQty',5,'maxQty',9,'unitPrice',15500),jsonb_build_object('minQty',10,'maxQty',19,'unitPrice',14400),jsonb_build_object('minQty',20,'maxQty',29,'unitPrice',13200),jsonb_build_object('minQty',30,'maxQty',49,'unitPrice',11900),jsonb_build_object('minQty',50,'unitPrice',10700))),

    jsonb_build_object('id','may-7','name','Proyector 4K Ultra HD','cat','Mayorista','description','Tecnologia hogar gadgets','price',64000,'stock',50,'img','','tier_prices',jsonb_build_array(jsonb_build_object('minQty',3,'maxQty',4,'unitPrice',64000),jsonb_build_object('minQty',5,'maxQty',9,'unitPrice',58900),jsonb_build_object('minQty',10,'maxQty',19,'unitPrice',56200),jsonb_build_object('minQty',20,'unitPrice',54000))),
    jsonb_build_object('id','may-8','name','TV Stick con Magis TV','cat','Mayorista','description','Tecnologia hogar gadgets','price',38900,'stock',50,'img','','tier_prices',jsonb_build_array(jsonb_build_object('minQty',5,'maxQty',9,'unitPrice',38900),jsonb_build_object('minQty',10,'maxQty',19,'unitPrice',36700),jsonb_build_object('minQty',20,'maxQty',39,'unitPrice',35490),jsonb_build_object('minQty',40,'unitPrice',39950))),
    jsonb_build_object('id','may-9','name','Camara foco 360','cat','Mayorista','description','Tecnologia hogar gadgets','price',18950,'stock',50,'img','','tier_prices',jsonb_build_array(jsonb_build_object('minQty',5,'maxQty',9,'unitPrice',18950),jsonb_build_object('minQty',10,'maxQty',19,'unitPrice',17900),jsonb_build_object('minQty',20,'maxQty',29,'unitPrice',16800),jsonb_build_object('minQty',30,'maxQty',49,'unitPrice',15000),jsonb_build_object('minQty',50,'unitPrice',13400))),
    jsonb_build_object('id','may-10','name','Game Stick 2.4 wireless','cat','Mayorista','description','Tecnologia hogar gadgets','price',37900,'stock',50,'img','','tier_prices',jsonb_build_array(jsonb_build_object('minQty',5,'maxQty',9,'unitPrice',37900),jsonb_build_object('minQty',10,'maxQty',19,'unitPrice',36900),jsonb_build_object('minQty',20,'maxQty',29,'unitPrice',34900),jsonb_build_object('minQty',30,'maxQty',49,'unitPrice',34000),jsonb_build_object('minQty',50,'unitPrice',32900))),
    jsonb_build_object('id','may-11','name','Aspiradora de mano','cat','Mayorista','description','Tecnologia hogar gadgets','price',15000,'stock',50,'img','','tier_prices',jsonb_build_array(jsonb_build_object('minQty',10,'maxQty',19,'unitPrice',15000),jsonb_build_object('minQty',20,'maxQty',39,'unitPrice',14000),jsonb_build_object('minQty',40,'unitPrice',11000))),
    jsonb_build_object('id','may-12','name','Maquina de Cortar el Pelo Economica','cat','Mayorista','description','Tecnologia hogar gadgets','price',9500,'stock',50,'img','','tier_prices',jsonb_build_array(jsonb_build_object('minQty',10,'maxQty',19,'unitPrice',9500),jsonb_build_object('minQty',20,'maxQty',39,'unitPrice',7900),jsonb_build_object('minQty',40,'unitPrice',6750))),
    jsonb_build_object('id','may-13','name','Aspiradora robot','cat','Mayorista','description','Tecnologia hogar gadgets','price',30900,'stock',50,'img','','tier_prices',jsonb_build_array(jsonb_build_object('minQty',3,'maxQty',4,'unitPrice',30900),jsonb_build_object('minQty',5,'maxQty',9,'unitPrice',29500),jsonb_build_object('minQty',10,'maxQty',19,'unitPrice',27700),jsonb_build_object('minQty',20,'maxQty',49,'unitPrice',24850),jsonb_build_object('minQty',50,'unitPrice',22600))),

    jsonb_build_object('id','rel-1','name','Smartwatch 7 Mayas','cat','Relojes','description','Relojes','price',19000,'stock',50,'img','','tier_prices',jsonb_build_array(jsonb_build_object('minQty',5,'maxQty',9,'unitPrice',19000),jsonb_build_object('minQty',10,'maxQty',19,'unitPrice',17000),jsonb_build_object('minQty',20,'maxQty',49,'unitPrice',14900),jsonb_build_object('minQty',50,'unitPrice',13700))),
    jsonb_build_object('id','rel-2','name','Apple Watch','cat','Relojes','description','Relojes','price',31000,'stock',50,'img','','tier_prices',jsonb_build_array(jsonb_build_object('minQty',5,'maxQty',9,'unitPrice',31000),jsonb_build_object('minQty',10,'maxQty',19,'unitPrice',29900),jsonb_build_object('minQty',20,'unitPrice',26500))),

    jsonb_build_object('id','may-19','name','Crema Karsell','cat','Mayorista','description','Belleza y moda','price',17800,'stock',50,'img','','tier_prices',jsonb_build_array(jsonb_build_object('minQty',5,'maxQty',9,'unitPrice',17800),jsonb_build_object('minQty',10,'maxQty',19,'unitPrice',16100),jsonb_build_object('minQty',20,'unitPrice',14500))),
    jsonb_build_object('id','may-20','name','Victorias Secret Body Splash','cat','Mayorista','description','Belleza y moda','price',18000,'stock',50,'img','','tier_prices',jsonb_build_array(jsonb_build_object('minQty',1,'maxQty',4,'unitPrice',18000),jsonb_build_object('minQty',5,'maxQty',9,'unitPrice',14000),jsonb_build_object('minQty',10,'maxQty',19,'unitPrice',12800),jsonb_build_object('minQty',20,'maxQty',49,'unitPrice',10700),jsonb_build_object('minQty',50,'unitPrice',9900))),

    jsonb_build_object('id','may-14','name','ELFBAR 40K','cat','Mayorista','description','Vapos','price',25000,'stock',50,'img','','tier_prices',jsonb_build_array(jsonb_build_object('minQty',1,'maxQty',1,'unitPrice',25000),jsonb_build_object('minQty',2,'maxQty',2,'unitPrice',22500),jsonb_build_object('minQty',3,'maxQty',4,'unitPrice',21500),jsonb_build_object('minQty',5,'maxQty',9,'unitPrice',19800),jsonb_build_object('minQty',10,'maxQty',19,'unitPrice',19000),jsonb_build_object('minQty',20,'maxQty',49,'unitPrice',18000),jsonb_build_object('minQty',50,'unitPrice',16850))),
    jsonb_build_object('id','may-15','name','IGNITE V250 / V300','cat','Mayorista','description','Vapos','price',25000,'stock',50,'img','','tier_prices',jsonb_build_array(jsonb_build_object('minQty',1,'maxQty',1,'unitPrice',25000),jsonb_build_object('minQty',2,'maxQty',2,'unitPrice',22500),jsonb_build_object('minQty',3,'maxQty',4,'unitPrice',21500),jsonb_build_object('minQty',5,'maxQty',9,'unitPrice',19500),jsonb_build_object('minQty',10,'maxQty',19,'unitPrice',18500),jsonb_build_object('minQty',20,'maxQty',49,'unitPrice',18000),jsonb_build_object('minQty',50,'maxQty',99,'unitPrice',16900),jsonb_build_object('minQty',100,'unitPrice',16450))),
    jsonb_build_object('id','may-16','name','IGNITE V400','cat','Mayorista','description','Vapos','price',30000,'stock',50,'img','','tier_prices',jsonb_build_array(jsonb_build_object('minQty',1,'maxQty',1,'unitPrice',30000),jsonb_build_object('minQty',2,'maxQty',2,'unitPrice',28000),jsonb_build_object('minQty',3,'maxQty',4,'unitPrice',26000),jsonb_build_object('minQty',5,'maxQty',9,'unitPrice',24800),jsonb_build_object('minQty',10,'maxQty',19,'unitPrice',22900),jsonb_build_object('minQty',20,'maxQty',49,'unitPrice',21100),jsonb_build_object('minQty',50,'maxQty',99,'unitPrice',19290),jsonb_build_object('minQty',100,'unitPrice',18500))),

    jsonb_build_object('id','cel-1','name','Xiaomi Note 14 Pro+ 5G 12/512','cat','Celulares','description','Promo mayorista','price',375,'old',410,'stock',50,'img','','tier_prices','[]'::jsonb),
    jsonb_build_object('id','cel-2','name','Xiaomi Note 14 Pro+ 5G 8/256','cat','Celulares','description','Promo mayorista','price',320,'old',350,'stock',50,'img','','tier_prices','[]'::jsonb),
    jsonb_build_object('id','cel-3','name','Xiaomi Note 14 Pro 12/512','cat','Celulares','description','Promo mayorista','price',280,'old',310,'stock',50,'img','','tier_prices','[]'::jsonb),
    jsonb_build_object('id','cel-4','name','Xiaomi Note 14 Pro 8/256','cat','Celulares','description','Promo mayorista','price',235,'old',260,'stock',50,'img','','tier_prices','[]'::jsonb),
    jsonb_build_object('id','cel-5','name','Xiaomi Note 14 4G 8/256','cat','Celulares','description','Promo mayorista','price',180,'old',204,'stock',50,'img','','tier_prices','[]'::jsonb),
    jsonb_build_object('id','cel-6','name','Xiaomi Note 14 4G 6/128','cat','Celulares','description','Promo mayorista','price',160,'old',185,'stock',50,'img','','tier_prices','[]'::jsonb),
    jsonb_build_object('id','cel-7','name','Redmi 14C 16/256','cat','Celulares','description','Promo mayorista','price',115,'old',138,'stock',50,'img','','tier_prices','[]'::jsonb),
    jsonb_build_object('id','cel-8','name','Redmi 15C 16/256','cat','Celulares','description','Promo mayorista','price',150,'old',190,'stock',50,'img','','tier_prices','[]'::jsonb),
    jsonb_build_object('id','cel-9','name','Redmi 15C 4/128','cat','Celulares','description','Promo mayorista','price',120,'old',145,'stock',50,'img','','tier_prices','[]'::jsonb),
    jsonb_build_object('id','cel-10','name','Redmi A5 8/128','cat','Celulares','description','Promo mayorista','price',95,'old',120,'stock',50,'img','','tier_prices','[]'::jsonb),
    jsonb_build_object('id','cel-11','name','Poco X7 5G 12/512','cat','Celulares','description','Promo mayorista','price',280,'old',309,'stock',50,'img','','tier_prices','[]'::jsonb),
    jsonb_build_object('id','cel-12','name','Poco X7 Pro 5G 8/256','cat','Celulares','description','Promo mayorista','price',299,'old',327,'stock',50,'img','','tier_prices','[]'::jsonb),
    jsonb_build_object('id','cel-13','name','Samsung A56 5G 8/256','cat','Celulares','description','Promo mayorista','price',335,'old',370,'stock',50,'img','','tier_prices','[]'::jsonb),
    jsonb_build_object('id','cel-14','name','Motorola Edge 50 Fusion 5G 8/256','cat','Celulares','description','Promo mayorista','price',235,'old',265,'stock',50,'img','','tier_prices','[]'::jsonb),

    jsonb_build_object('id','perf-1','name','9PM','cat','Perfumes','description','Mas vendidos','price',45000,'stock',50,'img','','tier_prices','[]'::jsonb),
    jsonb_build_object('id','perf-2','name','9AM Dive','cat','Perfumes','description','Mas vendidos','price',47000,'stock',50,'img','','tier_prices','[]'::jsonb),
    jsonb_build_object('id','perf-3','name','Asad Bourbon','cat','Perfumes','description','Mas vendidos','price',44000,'stock',50,'img','','tier_prices','[]'::jsonb),
    jsonb_build_object('id','perf-4','name','Lattafa Khamrah','cat','Perfumes','description','Mas vendidos','price',45000,'stock',50,'img','','tier_prices','[]'::jsonb),
    jsonb_build_object('id','perf-5','name','Club de Nuit Intense Men 105ml','cat','Perfumes','description','Mas vendidos','price',53000,'stock',50,'img','','tier_prices','[]'::jsonb),
    jsonb_build_object('id','perf-6','name','Mandarin Sky','cat','Perfumes','description','Odyssey','price',45000,'stock',50,'img','','tier_prices','[]'::jsonb),
    jsonb_build_object('id','perf-7','name','Candee','cat','Perfumes','description','Odyssey','price',41000,'stock',50,'img','','tier_prices','[]'::jsonb),
    jsonb_build_object('id','perf-8','name','Aqua','cat','Perfumes','description','Odyssey','price',42000,'stock',50,'img','','tier_prices','[]'::jsonb),
    jsonb_build_object('id','perf-9','name','Mega H','cat','Perfumes','description','Odyssey','price',48000,'stock',50,'img','','tier_prices','[]'::jsonb),
    jsonb_build_object('id','perf-10','name','Bade Oud for Glory Negro','cat','Perfumes','description','Lattafa','price',42000,'stock',50,'img','','tier_prices','[]'::jsonb),
    jsonb_build_object('id','perf-11','name','Bade Honor & Glory Blanco','cat','Perfumes','description','Lattafa','price',42000,'stock',50,'img','','tier_prices','[]'::jsonb),
    jsonb_build_object('id','perf-12','name','Fakhar Negro','cat','Perfumes','description','Lattafa','price',41000,'stock',50,'img','','tier_prices','[]'::jsonb),
    jsonb_build_object('id','perf-13','name','Fakhar Dorado','cat','Perfumes','description','Lattafa','price',38000,'stock',50,'img','','tier_prices','[]'::jsonb),
    jsonb_build_object('id','perf-14','name','Fakhar Blanco','cat','Perfumes','description','Lattafa','price',41500,'stock',50,'img','','tier_prices','[]'::jsonb),
    jsonb_build_object('id','perf-15','name','Yara Candy','cat','Perfumes','description','Lattafa','price',40000,'stock',50,'img','','tier_prices','[]'::jsonb),
    jsonb_build_object('id','perf-16','name','Yara Rosa Eau','cat','Perfumes','description','Lattafa','price',42000,'stock',50,'img','','tier_prices','[]'::jsonb),
    jsonb_build_object('id','perf-17','name','Eclaire','cat','Perfumes','description','Lattafa','price',44000,'stock',50,'img','','tier_prices','[]'::jsonb),
    jsonb_build_object('id','perf-18','name','The Kingdom','cat','Perfumes','description','Premium','price',63000,'stock',50,'img','','tier_prices','[]'::jsonb),
    jsonb_build_object('id','perf-19','name','Club de Nuit Elixir','cat','Perfumes','description','Premium','price',63500,'stock',50,'img','','tier_prices','[]'::jsonb),
    jsonb_build_object('id','perf-20','name','Bharara King EDP 100ml','cat','Perfumes','description','Premium','price',75000,'stock',50,'img','','tier_prices','[]'::jsonb),
    jsonb_build_object('id','perf-21','name','French Avenue Liquid Brun','cat','Perfumes','description','Premium','price',63500,'stock',50,'img','','tier_prices','[]'::jsonb),
    jsonb_build_object('id','perf-22','name','Al Haramain Amber Oud Gold 120ml','cat','Perfumes','description','Exclusivos','price',71000,'stock',50,'img','','tier_prices','[]'::jsonb),
    jsonb_build_object('id','perf-23','name','Philos Pura','cat','Perfumes','description','Exclusivos','price',42000,'stock',50,'img','','tier_prices','[]'::jsonb)
  ) as items
)
insert into public.products (id,name,description,cat,img,price,old,tag,stock,compatible_models,colors,tier_prices)
select
  p->>'id',
  p->>'name',
  nullif(p->>'description','') as description,
  p->>'cat',
  coalesce(p->>'img','') as img,
  coalesce((p->>'price')::numeric,0),
  case when p ? 'old' then (p->>'old')::numeric else null end,
  nullif(p->>'tag','') as tag,
  coalesce((p->>'stock')::int,50),
  '["Universal"]'::jsonb,
  coalesce(p->'colors','[]'::jsonb),
  coalesce(p->'tier_prices','[]'::jsonb)
from data, jsonb_array_elements(data.items) p
on conflict (id) do update set
  name = excluded.name,
  description = excluded.description,
  cat = excluded.cat,
  img = excluded.img,
  price = excluded.price,
  old = excluded.old,
  stock = excluded.stock,
  compatible_models = excluded.compatible_models,
  colors = excluded.colors,
  tier_prices = excluded.tier_prices;
