/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SantiagovillalbaRouteImport } from './routes/santiagovillalba'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SantiagovillalbaRoute = SantiagovillalbaRouteImport.update({
  id: '/santiagovillalba',
  path: '/santiagovillalba',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/santiagovillalba': typeof SantiagovillalbaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/santiagovillalba': typeof SantiagovillalbaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/santiagovillalba': typeof SantiagovillalbaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/santiagovillalba'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/santiagovillalba'
  id: '__root__' | '/' | '/santiagovillalba'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SantiagovillalbaRoute: typeof SantiagovillalbaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/santiagovillalba': {
      id: '/santiagovillalba'
      path: '/santiagovillalba'
      fullPath: '/santiagovillalba'
      preLoaderRoute: typeof SantiagovillalbaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SantiagovillalbaRoute: SantiagovillalbaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
